# Arquivo: netlify.toml (na raiz do projeto)

# Esta regra é a mais importante.
# Ela diz ao Netlify: "Se você não encontrar um arquivo específico (status 404),
# em vez de mostrar a página de erro, simplesmente sirva o arquivo /index.html".
# Isso resolve problemas de atualização de página (F5) e redirecionamento em sites de página única (SPAs).
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
